import { test, expect } from '@playwright/test';

const senators = [
    "Tommy Tuberville, AL",
    "Katie Britt, AL",
    "Lisa Murkowski, AK",
    "Dan Sullivan, AK",
    "Ruben Gallego, AZ",
    "Mark Kelly, AZ",
    "John Boozman, AR",
    "Tom Cotton, AR",
    "Adam Schiff, CA",
    "Alex Padilla, CA",
    "Michael Bennet, CO",
    "John Hickenlooper, CO",
    "Richard Blumenthal, CT",
    "Christopher Murphy, CT",
    "Christopher Coons, DE",
    "Lisa Blunt Rochester, DE",
    "Rick Scott, FL",
    "Ashley Moody, FL",
    "Jon Ossoff, GA",
    "Raphael Warnock, GA",
    "Mazie Hirono, HI",
    "Brian Schatz, HI",
    "James Risch, ID",
    "Mike Crapo, ID",
    "Richard Durbin, IL",
    "Tammy Duckworth, IL",
    "Todd Young, IN",
    "Jim Banks, IN",
    "Chuck Grassley, IA",
    "Joni Ernst, IA",
    "Jerry Moran, KS",
    "Roger Marshall, KS",
    "Mitch McConnell, KY",
    "Rand Paul, KY",
    "Bill Cassidy, LA",
    "John Kennedy, LA",
    "Susan Collins, ME",
    "Angus King, ME",
    "Chris Van Hollen, MD",
    "Angela Alsobrooks, MD",
    "Ed Markey, MA",
    "Elizabeth Warren, MA",
    "Gary Peters, MI",
    "Elissa Slotkin, MI",
    "Amy Klobuchar, MN",
    "Tina Smith, MN",
    "Roger Wicker, MS",
    "Cindy Hyde-Smith, MS",
    "Josh Hawley, MO",
    "Eric Schmitt, MO",
    "Steve Daines, MT",
    "Tim Sheehy, MT",
    "Deb Fischer, NE",
    "Pete Ricketts, NE",
    "Catherine Cortez Masto, NV",
    "Jacky Rosen, NV",
    "Jeanne Shaheen, NH",
    "Maggie Hassan, NH",
    "Cory Booker, NJ",
    "Andy Kim, NJ",
    "Martin Heinrich, NM",
    "Ben Luj\u00e1n, NM",
    "Kirsten Gillibrand, NY",
    "Chuck Schumer, NY",
    "Thom Tillis, NC",
    "Ted Budd, NC",
    "John Hoeven, ND",
    "Kevin Cramer, ND",
    "Bernie Moreno, OH",
    "Jon Husted, OH",
    "James Lankford, OK",
    "Markwayne Mullin, OK",
    "Jeff Merkley, OR",
    "Ron Wyden, OR",
    "John Fetterman, PA",
    "Dave McCormick, PA",
    "Sheldon Whitehouse, RI",
    "Jack Reed, RI",
    "Lindsey Graham, SC",
    "Tim Scott, SC",
    "John Thune, SD",
    "Mike Rounds, SD",
    "Marsha Blackburn, TN",
    "Bill Hagerty, TN",
    "John Cornyn, TX",
    "Ted Cruz, TX",
    "Mike Lee, UT",
    "John Curtis, UT",
    "Bernie Sanders, VT",
    "Peter Welch, VT",
    "Mark Warner, VA",
    "Tim Kaine, VA",
    "Maria Cantwell, WA",
    "Patty Murray, WA",
    "Shelley Capito, WV",
    "Jim Justice, WV",
    "Tammy Baldwin, WI",
    "Ron Johnson, WI",
    "John Barrasso, WY",
    "Cynthia Lummis, WY",
];

/**
 * if this test fails it means one of two things:
 * 
 * 1. One or more senators from the list above is no longer in the 
 *    official phone book. The above list was generated by 5calls.
 *    Ask the 5 Calls API who it thinks the senators are now, and 
 *    update the above list.
 *    (I didn't want to call 5calls API in the tests).
 * 
 * 2. the XML file is no longer available, or changed format, and
 *    the build-time import in office_[id].json.ts silently failed
 *    during the build (it should have blown up.)
 **/

for (const senator of senators) {
    const name = senator.split(', ', 2)[0];
    const state = senator.split(', ', 2)[1];
    const last = name.split(' ').slice(1).join("_");
    const id = `${last}_${state}`;
    test(`has ${senator}`, async ({ request }) => {
        var response = await request.get(`/api/office_${id}.json`);
        await expect(response).toBeOK(); 
    });
};
